version: '3.1'

services:
  backend:
    build:
      context: .
      dockerfile: backend/dockerfile
    image: gif-zone-backend
    volumes:
      - ./backend/config/settings.docker.yml:/app/settings.yml:ro
    depends_on:
      - db
  frontend:
    image: nginx
    volumes:
      - ./frontend/config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/build:/usr/share/nginx/html/:ro
      - ./dev_config/keys:/etc/nginx/certs/test.gif.zone:ro
      - ./data:/var/www/gif.zone/data:ro
    depends_on:
      - backend
    ports:
      - "8000:80"
      - "8443:443"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: gif_zone
      POSTGRES_USER: gif_zone
      POSTGRES_PASSWORD: gif_zone
    ports:
      - 5432:5432
