version: '3.1'

services:
  backend:
    build:
      context: .
      dockerfile: backend/dockerfile
    image: gif-zone-backend
    volumes:
      - ./backend/config/settings.docker.yml:/app/settings.yml:ro
    depends_on:
      - db
    # ports:
    #   - "80:8080"
  frontend:
    build:
      context: .
      dockerfile: frontend/dockerfile
    image: gif-zone-frontend
    volumes:
      - ./frontend/config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    ports:
      - "8000:80"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: gif_zone
      POSTGRES_USER: gif_zone
      POSTGRES_PASSWORD: gif_zone
    ports:
      - 5432:5432
